=== jjdmol/LOFAR/trunk/SAS/OTB/MoM-OTDB-adapter/config/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.astron.nl/MoM-OTDB-adapter"
	xmlns:config="http://www.astron.nl/MoM-OTDB-adapter" elementFormDefault="qualified">

    <element name="config" type="config:MoM2OTDBAdapterType"></element>

    <complexType name="MoM2OTDBAdapterType">
    	<sequence>
    		<element name="mom2" type="config:MoM2ConfigType"/>
    		<choice>
    			<element name="otdb" type="config:OTDBConfigType"/>
    			<element name="stub" type="config:StubConfigType"/>
    		</choice>
    		<element name="adapter" type="config:AdapterConfigType"/>
    	</sequence>
    </complexType>
    
    <complexType name="MoM2ConfigType">
    	<sequence>
    		<element name="username" type="string"/>
    		<element name="password" type="string"/>
    		<element name="authurl" type="string"/>
    		<element name="mom2-import-url" type="string"/>
    		<element name="mom2-schemas-url" type="string"/>
    	</sequence>

    </complexType>
    <complexType name="RepositoryConfigType">
    	<sequence>
    		<element name="interval" type="integer"/>  
    	</sequence> 	
    </complexType>    
    <complexType name="OTDBConfigType">
    	<complexContent>
			<extension base="config:RepositoryConfigType">
		    	<sequence>
		     		<element name="rmihost" type="string"/>
		    		<element name="rmiport" type="integer"/>  
		    	</sequence> 				
			</extension>
		</complexContent>    

    </complexType>    
    <complexType name="StubConfigType">
    	<complexContent>
			<extension base="config:RepositoryConfigType">
			</extension>
		</complexContent>
    </complexType>      
     <complexType name="AdapterConfigType">
    	<sequence>
    		<element name="httpport" type="integer"/> 
     		<element name="keystore-location" type="string"/>
			<element name="keystore-password" type="string"/>
			<element name="trusted-keystore-location" type="string"/>
			<element name="trusted-keystore-password" type="string"/>
    	</sequence> 	
    </complexType> 
</schema>

=== jjdmol/LOFAR/trunk/SAS/OTB/MoM-OTDB-adapter/dist-sources/conf/config-otdb.xml
<?xml version="1.0" encoding="UTF-8"?>
<config:config xmlns:config="http://www.astron.nl/MoM-OTDB-adapter" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.astron.nl/MoM-OTDB-adapter ../src/config.xsd ">
	<config:mom2>
		<config:username>momotdbadapter</config:username>
		<config:password>momotdbadapter</config:password>
		<config:authurl>http://rdd-stage6.nfra.nl:8080/useradministration</config:authurl>
		<config:mom2-import-url>http://rdd-stage6.nfra.nl:8080/mom3/interface/importXML2.do</config:mom2-import-url>
		<config:mom2-schemas-url>http://rdd-stage6.nfra.nl:8080/mom3/schemas/</config:mom2-schemas-url>
	</config:mom2>
	<config:otdb>
		<config:interval>5</config:interval>
		<config:uvObservationTemplateId>5001</config:uvObservationTemplateId>
		<config:rmihost>lofar17.astron.nl</config:rmihost>
		<config:rmiport>10399</config:rmiport>
	</config:otdb>
	<config:adapter>
		<config:httpport>8082</config:httpport>
		<config:keystore-location>./keystores/mom-otdb-adapter-keystore.jks</config:keystore-location>
		<config:keystore-password>adapter</config:keystore-password>
		<config:trusted-keystore-location>./keystores/mom-otdb-adapter-trusted-keystore.jks</config:trusted-keystore-location>
		<config:trusted-keystore-password>adapter-trusted</config:trusted-keystore-password>
	</config:adapter>
</config:config>

=== jjdmol/LOFAR/trunk/SAS/OTB/MoM-OTDB-adapter/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config:config xmlns:config="http://www.astron.nl/MoM-OTDB-adapter" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.astron.nl/MoM-OTDB-adapter config.xsd ">
	<config:mom2>
		<config:username>config:username</config:username>
		<config:password>config:password</config:password>
		<config:authurl>config:authurl</config:authurl>
		<config:mom2-import-url>config:mom2-import-url</config:mom2-import-url>
		<config:mom2-schemas-url>dsfs</config:mom2-schemas-url>
	</config:mom2>
	<config:stub>
		<config:interval>3</config:interval>
	</config:stub>
	<config:adapter>
		<config:httpport>30</config:httpport>
		<config:keystore-location>config:keystore-location</config:keystore-location>
		<config:keystore-password>config:keystore-password</config:keystore-password>
		<config:trusted-keystore-location>config:trusted-keystore-location</config:trusted-keystore-location>
		<config:trusted-keystore-password>config:trusted-keystore-password</config:trusted-keystore-password>
	</config:adapter>
</config:config>
