=== jjdmol/LOFAR/branches/Cobalt-Task4554/support/tools/BaseSimGUI/basesim.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT   basesim     (simul+)>
<!ELEMENT   simul       (workholder,(simul|step|exstep)*,connect*)>
<!ELEMENT   step        (workholder)>
<!ELEMENT   exstep      EMPTY>
<!ELEMENT   workholder  (dataholder*)>
<!ELEMENT   dataholder  EMPTY>
<!ELEMENT   connect     EMPTY>

<!ATTLIST   workholder
                name    CDATA           #IMPLIED
                class   CDATA           #IMPLIED>

<!ATTLIST   simul
		name	CDATA		#REQUIRED
  		node	CDATA		#IMPLIED>

<!ATTLIST   step
                name    CDATA           #REQUIRED
                node    CDATA           #IMPLIED>

<!ATTLIST   exstep
                name    CDATA           #REQUIRED
                exname  CDATA           #REQUIRED
                node    CDATA           #IMPLIED
                src     CDATA           #REQUIRED>

<!ATTLIST   dataholder
                name    CDATA           #IMPLIED
		type	(in|out)	#REQUIRED>

<!ATTLIST   connect
                src     CDATA           #REQUIRED
                dest    CDATA           #REQUIRED
                rate    CDATA           #IMPLIED
                class   CDATA           #IMPLIED>

=== jjdmol/LOFAR/branches/LOFAR-preRelease-2_1/support/tools/BaseSimGUI/demo2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE basesim SYSTEM "basesim.dtd">
<basesim>
  <simul name="mySimul">

    <!-- WorkHolder definition; only one WH per Simul -->
    <workholder name="wh1">
      <dataholder name = "dh1" type="in"/>
      <dataholder name = "dh2" type="out"/>
    </workholder>

    <exstep name="simul1" exname="mySimul" src="lib.xml"/>
    <exstep name="simul2" exname="mySimul" src="lib.xml"/>
    <exstep name="simul3" exname="mySimul" src="lib.xml"/>
    <exstep name="simul4" exname="mySimul" src="lib.xml"/>

    <connect src="simul1" dest="simul2"/>
    <connect src="simul3" dest="simul4"/>
  </simul>
</basesim>

=== jjdmol/LOFAR/branches/Cobalt-Task4637/support/tools/BaseSimGUI/lib.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE basesim SYSTEM "basesim.dtd">
<basesim>
  <simul name="mySimul">

    <!-- WorkHolder definition; only one WH per Simul -->
    <workholder name="wh1">
      <dataholder name = "dh1" type="in"/>
      <dataholder name = "dh2" type="in"/>
      <dataholder name = "dh3" type="in"/>
      <dataholder name = "dh4" type="out"/>
      <dataholder name = "dh5" type="out"/>
      <dataholder name = "dh6" type="out"/>
    </workholder>


    <exstep name="myExStep1" exname="mySimul" src="demo1.xml" node="1"/>
    <exstep name="myExStep2" exname="mySimul" src="demo1.xml" node="1"/>
    <exstep name="myExStep3" exname="mySimul" src="demo1.xml" node="1"/>
    <exstep name="myExStep4" exname="mySimul" src="demo1.xml" node="2"/>
    <exstep name="myExStep5" exname="mySimul" src="demo1.xml" node="2"/>
    <exstep name="myExStep6" exname="mySimul" src="demo1.xml" node="2"/>

    <connect src="myExStep1" dest="myExStep4"/>
    <connect src="myExStep2" dest="myExStep5"/>
    <connect src="myExStep3" dest="myExStep6"/>

    <connect src=".dh1" dest="myExStep1.dh1"/>
    <connect src=".dh2" dest="myExStep2.dh1"/>
    <connect src=".dh3" dest="myExStep3.dh1"/>
    <connect src="myExStep4.dh2" dest=".dh4"/>
    <connect src="myExStep5.dh2" dest=".dh5"/>
    <connect src="myExStep6.dh2" dest=".dh6"/>

  </simul>
</basesim>

=== jjdmol/LOFAR/branches/LOFAR-Release-2_8/support/tools/BaseSimGUI/demo1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE basesim SYSTEM "basesim.dtd">
<basesim>
  <simul name="mySimul">

    <!-- WorkHolder definition; only one WH per Simul -->
    <workholder name="wh1">
      <dataholder name = "dh1" type="in"/>
      <dataholder name = "dh2" type="out"/>
    </workholder>

    <step name="myStep1">
        <workholder name="myWorkHolder" class="WH_Antenna">
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh2" type="out"/>
	</workholder>
    </step>

    <step name="myStep2">
        <workholder name="myWorkHolder" class="WH_Antenna">
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh2" type="in"/>
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh2" type="out"/>
	</workholder>
    </step>

    <step name="myStep3">
        <workholder name="myWorkHolder" class="WH_Antenna">
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh2" type="out"/>
	</workholder>
    </step>

    <step name="myStep4">
        <workholder name="myWorkHolder" class="WH_Antenna">
		<dataholder name="dh1" type="in"/>
		<dataholder name="dh2" type="out"/>
	</workholder>
    </step>

    <step name="myStep5">
        <workholder name="myWorkHolder" class="WH_Antenna">
		<dataholder name="dh2" type="in"/>
		<dataholder name="dh1" type="out"/>
		<dataholder name="dh1" type="out"/>
		<dataholder name="dh1" type="out"/>
		<dataholder name="dh1" type="out"/>
		<dataholder name="dh1" type="out"/>
		<dataholder name="dh1" type="out"/>
		<dataholder name="dh1" type="out"/>
		<dataholder name="dh1" type="out"/>
		<dataholder name="dh1" type="out"/>
		<dataholder name="dh1" type="out"/>
		<dataholder name="dh1" type="out"/>
		<dataholder name="dh1" type="out"/>
	</workholder>
    </step>
    
    <connect src="myStep5" dest="myStep2"/>
    <connect src="myStep2" dest="myStep3"/>
    <connect src="myStep3" dest="myStep4"/>
    <connect src="myStep5" dest="myStep1"/>
    <connect src="myStep1" dest="myStep3"/>

    <connect src=".dh1" dest="myStep5.dh2"/>
    <connect src="myStep4.dh2" dest=".dh2"/>
    

  </simul>
</basesim>
